# Generated by Django 4.1.3 on 2022-12-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos_solar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobrenos',
            name='title',
        ),
        migrations.AddField(
            model_name='sobrenos',
            name='title1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='sobrenos',
            name='title2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
    ]
